### ISSUE TITLE
Mac OS 10.13.6 Tells Me To Trash It

### ISSUE THREAD

**Issue by jamesmadelin** [AkdM/KnightTouchBar2000#10] opened 2018-11-20 16:58 UTC
Hi.... I downloaded the app but a dialogue pops up after unzipping when I click on it that simply says "You should move this to Trash"... with no explanation of why. When I tried a second time, so I could screen shot it, it did open but instantly quit unexpectedly.

**Comment by AkdM** [comment] 2018-11-20 17:00
Duplicate of #6 and #7

**Closed as completed by AkdM** 2018-11-20 17:00 UTC
